### ISSUE TITLE
This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by keyone2693** [suadev/InlineCssParser#3]
hi 
I get this error when trying to install it
 VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

> 21/12/2016 1:43:33 PM - Microsoft VSIX Installer
21/12/2016 1:43:34 PM - -------------------------------------------
21/12/2016 1:43:36 PM - Initializing Install...
21/12/2016 1:43:36 PM - Extension Details...
21/12/2016 1:43:36 PM - 	Identifier         : iiswebapp
21/12/2016 1:43:36 PM - 	Name               : IIS Web App Deployment Using WinRM
21/12/2016 1:43:36 PM - 	Author             : ms-vscs-rm
21/12/2016 1:43:36 PM - 	Version            : 1.4.1
21/12/2016 1:43:36 PM - 	Description        : Using WinRM connect to the host Computer, to deploy a Web project using Web Deploy or a SQL DB using sqlpackage.exe.
21/12/2016 1:43:36 PM - 	Locale             : en-US
21/12/2016 1:43:36 PM - 	MoreInfoURL        : 
21/12/2016 1:43:36 PM - 	InstalledByMSI     : False
21/12/2016 1:43:36 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
21/12/2016 1:43:36 PM - 
21/12/2016 1:43:37 PM - 	SignatureState     : Unsigned
21/12/2016 1:43:37 PM - 	Supported Products : 
21/12/2016 1:43:37 PM - 		Microsoft.VisualStudio.Services
21/12/2016 1:43:37 PM - 			Version : 
21/12/2016 1:43:37 PM - 
21/12/2016 1:43:37 PM - 	References         : 
21/12/2016 1:43:37 PM - Signature Details...
21/12/2016 1:43:37 PM - 	Extension is not signed.
21/12/2016 1:43:37 PM - 
21/12/2016 1:43:37 PM - Searching for applicable products...
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio Professional 2015
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio Community 2015
21/12/2016 1:43:40 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
21/12/2016 1:43:40 PM - Found installed product - Global Location
21/12/2016 1:43:40 PM - Found installed product - ssms
21/12/2016 1:43:40 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by suadev** [comment]
@keyone2693, The extension supports Visual Studio 2013, 2015, 2017. 

Just not sure about the latest release of 2017. What is your VS version

**Comment by Mrsevic** [comment]
I am also experiencing the same problem.

**Comment by suadev** [comment]
@Mrsevic which fork exactly are out talking about?  

Supporting VS 2019 is not a big deal, but i have not spare time yet

**Comment by Mrsevic** [comment]
'Evening, this one:
https://github.com/sathyarajv/InlineCssParser/tree/patch-1

Works fine for me. VS 2019 support should be trivial as well, I will try to do the build this weekend. The only issues is that extension is a not that consistent all the time but you did a good job nevertheless.

**Comment by suadev** [comment]
It looks like @sathyarajv did it for VS2017. 

Ok i ll do my best to support VS 2019 soon.  Between, in which cases it works unconsistent? Feel free to create an issue. Thanks.

**Comment by keyone2693** [comment]
i need this one for vs 2019

**Comment by keyone2693** [comment]
I change these ones 
and after build it for myself, it's working fine now
![1](https://user-images.githubusercontent.com/19763704/75965780-85dfaa80-5ede-11ea-8244-6b7a5734730c.PNG)
![2](https://user-images.githubusercontent.com/19763704/75965783-87a96e00-5ede-11ea-91a6-9b774f1db9c3.PNG)

**Comment by suadev** [comment]
@keyone2693 i will be publishing a new version that support vs 2019 very soon

**Comment by suadev** [comment]
@keyone2693  @Mrsevic  Done.

https://marketplace.visualstudio.com/items?itemName=SuatKOSE.InlineStyleParserforHtmlFiles
