### ISSUE TITLE
Length cannot be less than zero

### ISSUE THREAD

**Issue by Mrsevic** [suadev/InlineCssParser#5]
Using the VS 2017 fork, in certain pages where there is usually(and unfortunately) heavy use of razor logic I keep receiving this error:

![image](https://user-images.githubusercontent.com/7526103/75962360-ec0b0400-5ec3-11ea-90c3-b3ae55c40df6.png)

Will try to create some repo later on but I thought that you might have had encountered this issue.

Thanks

**Comment by suadev** [comment]
@Mrsevic thaks for reporting the issue. 
Can you share your sample file please?

**Comment by suadev** [comment]
@Mrsevic  i have just upgraded for installing on VS 2019. (not published on market yet) 
But i can not reproduce this issuse, so i need you to send your html file.

**Comment by Mrsevic** [comment]
I have installed this version on my VS 2017 installation and immediately afterwards I got some error. Will take a look at Activity log xml when I get back at work.
